#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pygame
Version  : 2.1.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/9a/50/67767e5586a45e7e7b02e6f0e07853f8fcb81b54c66db6278f1a1344491f/pygame-2.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/9a/50/67767e5586a45e7e7b02e6f0e07853f8fcb81b54c66db6278f1a1344491f/pygame-2.1.2.tar.gz
Summary  : Python Game Development
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause LGPL-2.1 Libpng MIT Zlib
Requires: pypi-pygame-license = %{version}-%{release}
Requires: pypi-pygame-python = %{version}-%{release}
Requires: pypi-pygame-python3 = %{version}-%{release}
BuildRequires : SDL2-dev
BuildRequires : SDL2_image-dev
BuildRequires : SDL2_mixer-dev
BuildRequires : SDL2_ttf-dev
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(x11)
BuildRequires : portmidi-dev
BuildRequires : python3-dev

%description
.. image:: https://raw.githubusercontent.com/pygame/pygame/main/docs/pygame_logo.svg
:alt: pygame
:target: https://www.pygame.org/

%package dev
Summary: dev components for the pypi-pygame package.
Group: Development
Provides: pypi-pygame-devel = %{version}-%{release}
Requires: pypi-pygame = %{version}-%{release}

%description dev
dev components for the pypi-pygame package.


%package license
Summary: license components for the pypi-pygame package.
Group: Default

%description license
license components for the pypi-pygame package.


%package python
Summary: python components for the pypi-pygame package.
Group: Default
Requires: pypi-pygame-python3 = %{version}-%{release}

%description python
python components for the pypi-pygame package.


%package python3
Summary: python3 components for the pypi-pygame package.
Group: Default
Requires: python3-core
Provides: pypi(pygame)

%description python3
python3 components for the pypi-pygame package.


%prep
%setup -q -n pygame-2.1.2
cd %{_builddir}/pygame-2.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648665531
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pygame
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/500bbacec5d91f0bbdf53a86846bb3a3e5026283
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.fluidsynth.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/731a8eff333b8f7053ab2220511b524c87a75923
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/45177cdb4b0a4675541af8784ef0f11a574b646d
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.opusfile.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/97fc36e24fee3b70a149a12588b0d6a14a30f49d
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.png.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/ddad81444c937f22e749ab9518058682953b1cdb
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.portmidi.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/47583eae99b8be974577bd0b35438f8b7b12bb92
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.sdl2.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/5d118dd9f68514e2e8c0cee82a51e5672fa61a05
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.sdl2_image.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/e46696ddcdee46a0a69564af93818f7fb86486f1
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.sdl2_mixer.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/adb8eef305226659243625d44cdf52e3c4fe55d7
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.sse2neon-h.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/3a77c57187d1a25b6a049983735528f737fbafec
cp %{_builddir}/pygame-2.1.2/docs/licenses/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/00a7d2da8ecfab54b7859887e65ff57c71774f84
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/python3.10/pygame/_camera.h
/usr/include/python3.10/pygame/_pygame.h
/usr/include/python3.10/pygame/_surface.h
/usr/include/python3.10/pygame/camera.h
/usr/include/python3.10/pygame/font.h
/usr/include/python3.10/pygame/freetype.h
/usr/include/python3.10/pygame/include/_pygame.h
/usr/include/python3.10/pygame/include/bitmask.h
/usr/include/python3.10/pygame/include/pgcompat.h
/usr/include/python3.10/pygame/include/pgimport.h
/usr/include/python3.10/pygame/include/pgplatform.h
/usr/include/python3.10/pygame/include/pygame.h
/usr/include/python3.10/pygame/include/pygame_bufferproxy.h
/usr/include/python3.10/pygame/include/pygame_font.h
/usr/include/python3.10/pygame/include/pygame_freetype.h
/usr/include/python3.10/pygame/include/pygame_mask.h
/usr/include/python3.10/pygame/include/pygame_mixer.h
/usr/include/python3.10/pygame/include/sse2neon.h
/usr/include/python3.10/pygame/mask.h
/usr/include/python3.10/pygame/mixer.h
/usr/include/python3.10/pygame/palette.h
/usr/include/python3.10/pygame/pgarrinter.h
/usr/include/python3.10/pygame/pgbufferproxy.h
/usr/include/python3.10/pygame/pgcompat.h
/usr/include/python3.10/pygame/pgopengl.h
/usr/include/python3.10/pygame/pgplatform.h
/usr/include/python3.10/pygame/pygame.h
/usr/include/python3.10/pygame/scrap.h
/usr/include/python3.10/pygame/surface.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pygame/00a7d2da8ecfab54b7859887e65ff57c71774f84
/usr/share/package-licenses/pypi-pygame/3a77c57187d1a25b6a049983735528f737fbafec
/usr/share/package-licenses/pypi-pygame/45177cdb4b0a4675541af8784ef0f11a574b646d
/usr/share/package-licenses/pypi-pygame/47583eae99b8be974577bd0b35438f8b7b12bb92
/usr/share/package-licenses/pypi-pygame/500bbacec5d91f0bbdf53a86846bb3a3e5026283
/usr/share/package-licenses/pypi-pygame/5d118dd9f68514e2e8c0cee82a51e5672fa61a05
/usr/share/package-licenses/pypi-pygame/731a8eff333b8f7053ab2220511b524c87a75923
/usr/share/package-licenses/pypi-pygame/97fc36e24fee3b70a149a12588b0d6a14a30f49d
/usr/share/package-licenses/pypi-pygame/adb8eef305226659243625d44cdf52e3c4fe55d7
/usr/share/package-licenses/pypi-pygame/ddad81444c937f22e749ab9518058682953b1cdb
/usr/share/package-licenses/pypi-pygame/e46696ddcdee46a0a69564af93818f7fb86486f1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
