#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pygame
Version  : 2.1.2
Release  : 10
URL      : https://files.pythonhosted.org/packages/9a/50/67767e5586a45e7e7b02e6f0e07853f8fcb81b54c66db6278f1a1344491f/pygame-2.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/9a/50/67767e5586a45e7e7b02e6f0e07853f8fcb81b54c66db6278f1a1344491f/pygame-2.1.2.tar.gz
Summary  : Python Game Development
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause FTL HPND IJG LGPL-2.1 Libpng Zlib
BuildRequires : SDL2-dev
BuildRequires : SDL2_image-dev
BuildRequires : SDL2_mixer-dev
BuildRequires : SDL2_ttf-dev
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(x11)
BuildRequires : portmidi-dev
BuildRequires : python3-dev

%description
.. image:: https://raw.githubusercontent.com/pygame/pygame/main/docs/pygame_logo.svg
:alt: pygame
:target: https://www.pygame.org/

%prep
%setup -q -n pygame-2.1.2
cd %{_builddir}/pygame-2.1.2
pushd ..
cp -a pygame-2.1.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666707220
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pygame
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/500bbacec5d91f0bbdf53a86846bb3a3e5026283 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.fluidsynth.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/731a8eff333b8f7053ab2220511b524c87a75923 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.freetype.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/1b299099e16ad96ebf53e67391685d9d0a51b368 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.jpeg.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/4136a0b0a031b9fd8eb7fe1b804e2a5dfea244f8 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.mpg123.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/49a448135eea9423f83ed5a187b4af9629fcf259 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.numpy.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/a5c2366a79c54fc80166e827d070677445e98fb3 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/45177cdb4b0a4675541af8784ef0f11a574b646d || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.opus.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/58babeb2cff60082cfab816c65a2db16536e61e3 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.opusfile.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/97fc36e24fee3b70a149a12588b0d6a14a30f49d || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.png.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/ddad81444c937f22e749ab9518058682953b1cdb || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.portmidi.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/47583eae99b8be974577bd0b35438f8b7b12bb92 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.sdl2.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/5d118dd9f68514e2e8c0cee82a51e5672fa61a05 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.sdl2_image.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/e46696ddcdee46a0a69564af93818f7fb86486f1 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.sdl2_mixer.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/adb8eef305226659243625d44cdf52e3c4fe55d7 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.sdl_gfx.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/5018d8de54192aa20d63f52624e4414d5f2c5c05 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.tiff.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/750cb144bad0eeb8301b7e753d88db30a4d97c80 || :
cp %{_builddir}/pygame-%{version}/docs/licenses/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/pypi-pygame/00a7d2da8ecfab54b7859887e65ff57c71774f84 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
